In [1]:
import numpy as np

In [21]:
a = np.array([1, 2, 3], dtype='int32')
print (a)

[1 2 3]


In [7]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [15]:
a.dtype

dtype('int16')

In [17]:
b.dtype

dtype('float64')

In [19]:
a.size

3

In [22]:
a.itemsize

4

In [23]:
a.size * a.itemsize

12

In [24]:
a.nbytes

12

In [25]:
b.itemsize

8

In [26]:
b.nbytes

48

In [28]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
a.shape

(2, 7)

In [30]:
a[1, 5]

13

In [32]:
a[1, -2]

13

In [33]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
a[:, 2]

array([ 3, 10])

In [36]:
a[0, 1:6:2]

array([2, 4, 6])

In [37]:
a[1, 5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
a[:, 2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [40]:
a[:, 2]= [1, 2]
print (a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [42]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
b[0, 1, 1]

4

In [44]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [46]:
b[:, 1, :] = [[9, 9], [8, 8]] # shape should match, otherwise It will give error
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
