In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype='int32')
print (a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
a.size

3

In [11]:
a.itemsize

4

In [12]:
a.size * a.itemsize

12

In [13]:
a.nbytes

12

In [14]:
b.itemsize

8

In [15]:
b.nbytes

48

In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

In [18]:
a[1, 5]

13

In [19]:
a[1, -2]

13

In [20]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
a[:, 2]

array([ 3, 10])

In [22]:
a[0, 1:6:2]

array([2, 4, 6])

In [23]:
a[1, 5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
a[:, 2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [25]:
a[:, 2]= [1, 2]
print (a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [26]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
b[0, 1, 1]

4

In [28]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [29]:
b[:, 1, :] = [[9, 9], [8, 8]] # shape should match, otherwise It will give error
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [30]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [33]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
np.random.rand(4, 2)

array([[0.13076145, 0.18873305],
       [0.75498861, 0.83597217],
       [0.74002593, 0.62720578],
       [0.55705452, 0.40874759]])

In [35]:
np.random.random_sample(a.shape)

array([[0.26673242, 0.78436711, 0.65259542, 0.36557477, 0.8268477 ,
        0.49692634, 0.06596483],
       [0.09335731, 0.90868308, 0.33531207, 0.30626541, 0.05188174,
        0.03459078, 0.52536173]])

In [36]:
np.random.randint(7, size=(3, 3))

array([[6, 5, 3],
       [2, 4, 0],
       [4, 5, 4]])

In [37]:
np.random.randint(4, 7, size=(3, 3))

array([[5, 4, 6],
       [4, 4, 4],
       [5, 5, 4]])

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
arr = np.array([[1, 2, 3]])
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
output = np.ones((5,5))
print (output)

z = np.zeros((3, 3))
z[1, 1] = 9
print (z)

output[1:-1, 1:-1] = z
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print (a)

[1 2 3]


In [42]:
a = np.array([1, 2, 3, 4])
print (a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [44]:
a - 2

array([-1,  0,  1,  2])

In [45]:
a * 2

array([2, 4, 6, 8])

In [46]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [47]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [48]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [49]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [50]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [51]:
a * b

array([1, 0, 3, 0])

In [52]:
a = np.ones((2, 3))
print (a)

b = np.full((3, 2), 2)
print (b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [53]:
c = np.identity(3)
np.linalg.det(c) # determinant

1.0

In [54]:
stats = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.min(stats)

1

In [56]:
np.max(stats)

8

In [57]:
np.min(stats, axis=1)

array([1, 5])

In [58]:
np.max(stats, axis=1)

array([4, 8])

In [59]:
np.sum(stats)

36

In [60]:
np.sum(stats, axis=1)

array([10, 26])

In [61]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print (before)

[[1 2 3 4]
 [5 6 7 8]]


In [62]:
after = before.reshape((8, 1))
print (after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [63]:
after = before.reshape((4, 2))
print (after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
after = before.reshape((2, 2, 2))
print (after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [65]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack((v1, v2, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [66]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [67]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [68]:
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [69]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [70]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [71]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 3, 8]]

array([2, 4, 9])

In [73]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [74]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [75]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [76]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])